### ISSUE TITLE
MAINTENANCE: fix Jupyter Book pre-deployment via Netlify

### ISSUE THREAD

**Issue by soerenthomsen** [OceanGlidersCommunity/DepthAverageCurrents_SOP#107]
I just write down this issue to keep track of it. In early December I might have some time for some maintenance work here. FYI: @callumrollo I want to use these real issue to show some friends Jupyter Book in real action.

**Comment by callumrollo** [comment]
Resolved with @soerenthomsen today :1st_place_medal:
